version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432
    volumes:
      - /yourdir/npb-analysis/docker/initdb:/docker-entrypoint-initdb.d
  postgres-gui:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8080:8081"
    environment:
      - DATABASE_URL=postgres://test:postgres@postgres:5432/test?sslmode=disable
    depends_on:
      - postgres