version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432
    volumes:
      - /{yourdir}/npb-analysis/docker/initdb:/docker-entrypoint-initdb.d
  postgres-gui:
    restart: always
    image: donnex/pgweb
    command: -s --bind=0.0.0.0 --listen=8080 --url postgresql://test:@postgres/test?sslmode=disable
    links:
      - postgres:postgres
    ports:
      - "8080:8080"