name: Runs test
on: push

jobs:
  backend-test:
    name: Backend test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.15.6

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run test
      run: go test -v ./...
