name: Runs test
on: push

jobs:
  backend-test:
    name: Backend test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.18.3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run test
      run: go test -v ./...

  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: yarn install
        run: yarn install
        working-directory: ./frontend/
      - name: Run test
        run: yarn test
        working-directory: ./frontend/